version: '3'

tasks:
  default:
    cmds:
      - task: build

  vars:
    VERSION:
      sh: git describe --tags --always --dirty

  build:
    desc: Build the binary
    cmds:
      - go build -ldflags "-X github.com/SuzumiyaAoba/via/internal/cli.Version={{.VERSION}}" -o vv ./cmd/vv

  test:
    desc: Run tests
    cmds:
      - go test ./...

  coverage:
    desc: Run tests with coverage
    cmds:
      - go test ./... -coverprofile=coverage.out
      - go tool cover -func=coverage.out

  coverage-html:
    desc: Generate HTML coverage report
    cmds:
      - go test ./... -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  clean:
    desc: Clean artifacts
    cmds:
      - rm -f vv
      - rm -rf dist
      - rm -f coverage.out coverage.html

  release:
    desc: Create a snapshot release
    cmds:
      - goreleaser release --snapshot --clean
